/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class FileSystem */

#ifndef _Included_FileSystem
#define _Included_FileSystem
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     FileSystem
 * Method:    fileSystem
 * Signature: (Ljava/lang/String;)LFileInfo;
 */
JNIEXPORT jobject JNICALL Java_FileSystem_fileSystem
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
