/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class FileSystem */

#ifndef _Included_FileSystem
#define _Included_FileSystem
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     FileSystem
 * Method:    nativeMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_FileSystem_nativeMethod
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
